# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../src/gui/AddServerWindow.ui'
#
# Created: Mon Apr 12 11:59:55 2010
#      by: PyQt4 UI code generator 4.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_AddServerWindow(object):
    def setupUi(self, AddServerWindow):
        AddServerWindow.setObjectName("AddServerWindow")
        AddServerWindow.setWindowModality(QtCore.Qt.WindowModal)
        AddServerWindow.resize(640, 328)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/Plus-32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AddServerWindow.setWindowIcon(icon)
        self.formLayout = QtGui.QFormLayout(AddServerWindow)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(AddServerWindow)
        self.label.setMinimumSize(QtCore.QSize(184, 0))
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.leHost = QtGui.QLineEdit(AddServerWindow)
        self.leHost.setObjectName("leHost")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.leHost)
        self.label_2 = QtGui.QLabel(AddServerWindow)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.sbPort = QtGui.QSpinBox(AddServerWindow)
        self.sbPort.setMaximum(2147483647)
        self.sbPort.setProperty("value", 22)
        self.sbPort.setObjectName("sbPort")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.sbPort)
        self.label_6 = QtGui.QLabel(AddServerWindow)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_6)
        self.leLabel = QtGui.QLineEdit(AddServerWindow)
        self.leLabel.setObjectName("leLabel")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.leLabel)
        self.rbUseExist = QtGui.QRadioButton(AddServerWindow)
        self.rbUseExist.setChecked(True)
        self.rbUseExist.setObjectName("rbUseExist")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.rbUseExist)
        self.rbCreate = QtGui.QRadioButton(AddServerWindow)
        self.rbCreate.setObjectName("rbCreate")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.rbCreate)
        self.rbRSA = QtGui.QRadioButton(AddServerWindow)
        self.rbRSA.setObjectName("rbRSA")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.rbRSA)
        self.lLoginPass = QtGui.QLabel(AddServerWindow)
        self.lLoginPass.setObjectName("lLoginPass")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.lLoginPass)
        self.cbLoginPass = QtGui.QComboBox(AddServerWindow)
        self.cbLoginPass.setObjectName("cbLoginPass")
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.cbLoginPass)
        self.lLogin = QtGui.QLabel(AddServerWindow)
        self.lLogin.setObjectName("lLogin")
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.lLogin)
        self.leLogin = QtGui.QLineEdit(AddServerWindow)
        self.leLogin.setObjectName("leLogin")
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.leLogin)
        self.lPassword = QtGui.QLabel(AddServerWindow)
        self.lPassword.setObjectName("lPassword")
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.lPassword)
        self.lePassword = QtGui.QLineEdit(AddServerWindow)
        self.lePassword.setObjectName("lePassword")
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.lePassword)
        self.buttonBox = QtGui.QDialogButtonBox(AddServerWindow)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.buttonBox)

        self.retranslateUi(AddServerWindow)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), AddServerWindow.close)
        QtCore.QObject.connect(self.rbUseExist, QtCore.SIGNAL("released()"), self.lLoginPass.show)
        QtCore.QObject.connect(self.rbUseExist, QtCore.SIGNAL("released()"), self.cbLoginPass.show)
        QtCore.QObject.connect(self.rbUseExist, QtCore.SIGNAL("released()"), self.lLogin.hide)
        QtCore.QObject.connect(self.rbUseExist, QtCore.SIGNAL("released()"), self.lPassword.hide)
        QtCore.QObject.connect(self.rbUseExist, QtCore.SIGNAL("released()"), self.leLogin.hide)
        QtCore.QObject.connect(self.rbUseExist, QtCore.SIGNAL("released()"), self.lePassword.hide)
        QtCore.QObject.connect(self.rbCreate, QtCore.SIGNAL("released()"), self.lLoginPass.hide)
        QtCore.QObject.connect(self.rbCreate, QtCore.SIGNAL("released()"), self.cbLoginPass.hide)
        QtCore.QObject.connect(self.rbCreate, QtCore.SIGNAL("released()"), self.lLogin.show)
        QtCore.QObject.connect(self.rbCreate, QtCore.SIGNAL("released()"), self.lPassword.show)
        QtCore.QObject.connect(self.rbCreate, QtCore.SIGNAL("released()"), self.leLogin.show)
        QtCore.QObject.connect(self.rbCreate, QtCore.SIGNAL("released()"), self.lePassword.show)
        QtCore.QObject.connect(self.rbRSA, QtCore.SIGNAL("released()"), self.lLoginPass.hide)
        QtCore.QObject.connect(self.rbRSA, QtCore.SIGNAL("released()"), self.cbLoginPass.hide)
        QtCore.QObject.connect(self.rbRSA, QtCore.SIGNAL("released()"), self.lLogin.show)
        QtCore.QObject.connect(self.rbRSA, QtCore.SIGNAL("released()"), self.lPassword.hide)
        QtCore.QObject.connect(self.rbRSA, QtCore.SIGNAL("released()"), self.leLogin.show)
        QtCore.QObject.connect(self.rbRSA, QtCore.SIGNAL("released()"), self.lePassword.hide)
        QtCore.QMetaObject.connectSlotsByName(AddServerWindow)

    def retranslateUi(self, AddServerWindow):
        AddServerWindow.setWindowTitle(QtGui.QApplication.translate("AddServerWindow", "Add a server", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("AddServerWindow", "Host (IP or Domain Name) :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("AddServerWindow", "Port :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("AddServerWindow", "Label for the server :", None, QtGui.QApplication.UnicodeUTF8))
        self.rbUseExist.setText(QtGui.QApplication.translate("AddServerWindow", "Use existing login/password", None, QtGui.QApplication.UnicodeUTF8))
        self.rbCreate.setText(QtGui.QApplication.translate("AddServerWindow", "Use new login/password", None, QtGui.QApplication.UnicodeUTF8))
        self.rbRSA.setText(QtGui.QApplication.translate("AddServerWindow", "Use RSA key", None, QtGui.QApplication.UnicodeUTF8))
        self.lLoginPass.setText(QtGui.QApplication.translate("AddServerWindow", "Login and password to use :", None, QtGui.QApplication.UnicodeUTF8))
        self.lLogin.setText(QtGui.QApplication.translate("AddServerWindow", "Login :", None, QtGui.QApplication.UnicodeUTF8))
        self.lPassword.setText(QtGui.QApplication.translate("AddServerWindow", "Password :", None, QtGui.QApplication.UnicodeUTF8))

import ressources_rc
